"""empty message

Revision ID: 699697027224
Revises: fc1dc59f17cc
Create Date: 2021-03-04 00:23:08.813083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699697027224'
down_revision = 'fc1dc59f17cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('adress', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('phone_num', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_num')
    op.drop_column('user', 'city')
    op.drop_column('user', 'adress')
    # ### end Alembic commands ###
