"""empty message

Revision ID: e800df3cc4da
Revises: 5f5b096ad43f
Create Date: 2021-01-30 15:49:50.964419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e800df3cc4da'
down_revision = '5f5b096ad43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_column('user', 'role')
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roles', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('role', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('role_users')
    # ### end Alembic commands ###
