"""empty message

Revision ID: fc1dc59f17cc
Revises: bb2d0a7c53b3
Create Date: 2021-02-14 21:57:14.356995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc1dc59f17cc'
down_revision = 'bb2d0a7c53b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('picture', sa.String(length=255), nullable=True))
    op.drop_column('device', 'pictures')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('pictures', mysql.TEXT(charset='utf8', collation='utf8_unicode_ci'), nullable=True))
    op.drop_column('device', 'picture')
    # ### end Alembic commands ###
