"""empty message

Revision ID: ffad193b06f1
Revises: 
Create Date: 2021-01-28 13:39:31.472612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffad193b06f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_column('role', 'role_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False))
    op.drop_column('role', 'name')
    # ### end Alembic commands ###
